### ISSUE TITLE
this workflow is a crime against humanity and you should never be allowed to touch a programming language again

### ISSUE THREAD

**Issue by Weigurde** [Minecraft-3DS-Community/minecraft-3ds-unistore#1]
1. literally any fucking text editor that i have ever used has had an actual proper find and replace tool, notepad, wordpad, vs code, codium, monaco, hxd, hexed.it, nano, micro, pico, grep, vi, ed, vim, neovim, even discord - why the fuck are you using a cloud-based wysiwyg text formatter for programming? are you brain damaged? did your mother get an alcoholism problem during her pregnancy?
2. why are you using a shitty fucking webapp made by some random person on a fucking meta web development tool? it's literally just a regex, go in any ide with regex support for ctrl + h and use `\r\n|\r|\n` as your find and `\n` as your replace
3. why are you using github as an ide and not an actual full ide? you do realise you're missing out on a lot of features (including your beloved ctrl + h)
4. why do we need a separate json validator? use your eyes, json is explicitly a human readable notation for a reason - this isn't a binary format

**Comment by Cracko298** [comment]
Looks like somebody had woken up on the wrong side of bed... whilst I agree GitHub isn't an IDE. This web app for 3ds is the same as Universal Updater (homebrew for Installeling 3ds CFW).

This is an obvious joke-like issue. And should be closed.

**Comment by susbaconhairman** [comment]
lmao average 4channer
