### ISSUE TITLE
Properly credit me

### ISSUE THREAD

**Issue by ghost** [Minecraft-3DS-Community/Minecraft-3ds-unistore#3]
You may be making the store from Scratch, but the whole idea of a Minecraft 3DS Unistore is from me. This whole Unistore was made to replace mine, so it is based off of it.

**Comment by nawrek** [comment]
You are indeed credited properly, because you discovered the idea of unistore. We won't credit you more, because you dont have any items in our store. I am closing this and please do not open another request.
