### ISSUE TITLE
UPDATE REQUEST: Modernization MegaPack v1.4.0

### ISSUE THREAD

**Issue by wyndchyme** [Minecraft-3DS-Community/Minecraft-3ds-unistore#6]
Please update the MegaPack version on the UniStore to 1.4.0. The files can be found here: https://github.com/wyndchyme/mc3ds-modern

Additionally, please update the icon to this:
![icon](https://github.com/user-attachments/assets/0a43b79f-f247-419d-9a48-f98a12f93216)

If possible please add an action required screen recommending the user to uninstall the MegaPack before updating to a new version, and warning that the MegaPack overwrites most mods. 

Also please add the missing 'c' to 'Pack' _(as in MegaPack, not MegaPak)_

Love your work y'all. Thanks a bunch.

**Comment by wyndchyme** [comment]
Also please change the screenshots to the new ones found in readme.md.

**Comment by STBrian** [comment]
When I updated last time I noticed that the c was missing but I thought that was the style of the name xd

**Comment by nawrek** [comment]
updated :) check if everything is working correctly, u know I'm new to this. Thanks!

**Comment by wyndchyme** [comment]
Thanks a bunch!
