### ISSUE TITLE
Modernization MegaPack EUR installer is broken

### ISSUE THREAD

**Issue by wyndchyme** [Minecraft-3DS-Community/Minecraft-3ds-unistore#7]
Installing the EUR version of Modernization MegaPack creates no files in /luma/titles – this may affect the JPN version as well (untested) 

Thanks to Nikothewolf for bringing this to my attention

**Comment by wyndchyme** [comment]
It would seem the JPN version is affected too

**Comment by nawrek** [comment]
I don't know what the issue is. For now I reversed the megapack to 1.3.0 and I am trying to figure out what causes it.

**Comment by nawrek** [comment]
I figured it out and fixed it. Thanks for letting me know about this!
